name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install flask pytest pylint

    - name: Run Tests
      run: pytest

    - name: Run Code Quality Check
      run: pylint app/app.py